name: CI

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
      - beta
    paths-ignore:
      - 'docs/**'

permissions:
  contents: read
  checks: write # Required for codecov to create check annotations

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      - name: Lint the code
        run: npm run lint --if-present

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x] # Updated Node.js versions

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build --if-present
      - name: Run tests
        run: npm run test:cov
        env:
          CI: true
      - name: Upload code coverage
        uses: codecov/codecov-action@v4
        if: matrix.node-version == '20.x' # Updated condition
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: Node.js ${{ matrix.node-version }}
          flags: unittests
