name: Documentation

on:
  workflow_dispatch: {}
  workflow_run:
    workflows:
      - Release
    branches:
      - main
    types:
      - requested
  release:
    types:
      - released

permissions:
  contents: write # Required for peaceiris/actions-gh-pages to deploy to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build documentation
        run: npm run docs:build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs/.vuepress/dist
